### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by GeorgeHahn** [Ackara/Plaid.NET#15]
I know you said you'd do this - I just want to track it somewhere. Is there anything I can do to help get this release out? Thanks!

**Comment by Ackara** [comment]
6/10 of my unit-test failed, so I held back. 

![image](https://user-images.githubusercontent.com/4080902/71819698-0dd24100-3063-11ea-9bf0-9b418c9a334c.png)

If your interested in running the tests. create a file called secrets.json at the root of the project (where the .sln file lives) and provide the following values.

```json
"plaid":
  {
    "secret": "",
    "client_id": "",
    "public_key": ""
  }
```

---

I plan on updating the library to the latest version eventually. Hopefully sometime this month or the next. When I released the first version years ago I realized they only supported USA based banks after the fact. Now it seems they have expanded beyond the USA, I am very interested to try it out again.

With that said, maintaining the library have not being a top priority, so I appreciate your help. If you have any question I will gladly answer.

Thank you

**Comment by GeorgeHahn** [comment]
Thanks for the info! I'm having some trouble getting the tests to build on dotnet core. [This package](https://www.nuget.org/packages/dotnet-t4-project-tool/) should get text templating working, but it looks like the csproj also needs some work. I'll take another look later this week if I have a good chunk of time.

**Comment by Ackara** [comment]
I converted the test project to netcore  and remove that .tt file (is was no longer in use)

**Comment by GeorgeHahn** [comment]
Thanks! I was able to get all tests to pass with some minor modifications. Let me know if you'd like a PR for these.

It looks like more tests pass if an access token is added to `secrets.json`. I created an access token that has transactions, identity, and income products. My account has the default API version set to `2019-05-29`.

`FetchUserIdentityAsync_should_retrieve_the_personal_info_of_an_user`: `result.Identity` is null, so `result.Identity.Names.Length.ShouldBeGreaterThan(0);` fails. This appears to match the API docs.

`FetchIncomeAsync_should_retrieve_the_monthly_earnings_of_an_user`: `result.Item` is null, so `result.Item.ShouldNotBeNull();` fails. The docs show `item` in the `/income/get` response, but it is omitted from actual API responses (observed in test & in standalone queries).

`FetchInstitutionsAsync_should_retrieve_a_list_of_banks_that_matches_a_specified_query`: It doesn't look like there are any results for `tartan`. Changing query to 'citi' gave success.

**Comment by Ackara** [comment]
Sure the mods seem to make sense.

**Comment by GeorgeHahn** [comment]
Hi! Any remaining blockers on this?

**Comment by Ackara** [comment]
There is still one more test that is failing `FetchAccountInfoAsync_should_retrieve_the_routing_numbers_of_an_user_accounts`

**Comment by Ackara** [comment]
System.AggregateException: One or more errors occurred. (Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Acklann.Plaid.Auth.GetAccountInfoResponse+AccountIdentifiers' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

**Comment by GeorgeHahn** [comment]
That's helpful, thanks. Fix PR is up. Weirdly enough, Json.NET happily tries to serialize Bacs/International accounts into an EftAccounts type for me instead of throwing like it does for you.

**Comment by Ackara** [comment]
The test is not passing cuz I need a key, but since you seem to really want the update push to nuget I'm willing to trust you and push despite the fact.  Should I?

**Comment by GeorgeHahn** [comment]
You should be able to add your current sandbox account token into the `intl_access_token` to pass the intl test I added. We should probably talk about reducing test flakiness and getting CI running in the future - maybe using the comments from #18 as a starting point?

I'd certainly appreciate a `0.10.0` update!

**Comment by Ackara** [comment]
yes, the test do need reworking and ci would be nice. I pushed to nuget
