### ISSUE TITLE
ExchangeTokenRequest doesn't inherit RequestBase

### ISSUE THREAD

**Issue by burkovsky** [Ackara/Plaid.NET#19]
Hello,
I'm sorry if it's done by design but I personally was really surprised when:
```
var request = new ExchangeTokenRequest
{
    PublicToken = publicToken
};
ExchangeTokenResponse response = await _plaidClient.ExchangeTokenAsync(request);
```
returned bad request saying client_id and secret are missed.

I started digging and found out that `EnsureCredentials` method doesn't do anything because `ExchangeTokenRequest` doesn't inherit `RequestBase` (as other classes) so request parameters such as `Secret`/`ClientId` are not fallbacked with values from `PlaidClient`.

Thank you!

**Comment by danports** [comment]
Yeah, I was confused by this behavior too. 😕

**Comment by pdubb29** [comment]
@burkovsky this can be closed now due to the fix PR being merged.
