### ISSUE TITLE
Missing currency codes in transaction responses

### ISSUE THREAD

**Issue by mvarga6** [Ackara/Plaid.NET#2]
The `Entity.Transaction` model is missing the `iso_currency_code` and `unofficial_currency_code` fields specified in the Plaid documentation. https://plaid.com/docs/#transactions

**Comment by jithinTechjini** [comment]
> The `Entity.Transaction` model is missing the `iso_currency_code` and `unofficial_currency_code` fields specified in the Plaid documentation. https://plaid.com/docs/#transactions

Even am not getting iso_currency_code and unofficial_currency_code on sandbox environment

**Comment by Ackara** [comment]
I will accept the pull request if guys don't mind fixing it.

**Comment by zainniazi** [comment]
@mvarga6 Let's close this issue, its available in the new release now.
