### ISSUE TITLE
Plaid.NET library not listed on Plaid community libraries

### ISSUE THREAD

**Issue by phoenixy1** [Ackara/Plaid.NET#22]
Hi @Ackara !

Thank you for writing this library!  I work at Plaid and was wondering if you would be interested in having this library included on our community libraries page?  I think a lot of Plaid users would benefit from it.  If you're interested, let me know and we'll add a link!

**Comment by Ackara** [comment]
Sure go ahead

**Comment by coolhome** [comment]
Congratulations @phoenixy1  and @Ackara! This can officially be closed.

![image](https://user-images.githubusercontent.com/700740/89201917-34684400-d580-11ea-9712-dfa95bc69e73.png)

**Comment by Ackara** [comment]
Thank you
