### ISSUE TITLE
Using decimal instead of float datatype

### ISSUE THREAD

**Issue by ahmad-moussawi** [Ackara/Plaid.NET#26]
Using float will lead to losing decimal precision when passing the float size limit,
Consider the number 345678.64
```cs
var a = Single.Parse("345678.64");
Console.WriteLine(a); // outputs 345678.62 
```
Check this thread for https://stackoverflow.com/questions/588004/is-floating-point-math-broken more info.

I can submit a PR if you agree on this.
Thanks.

**Comment by Ackara** [comment]
Yes, I would accept it.

**Comment by ahmad-moussawi** [comment]
Thanks @Ackara here is the PR https://github.com/Ackara/Plaid.NET/pull/27
