### ISSUE TITLE
Missing Status object in ItemResponse & Country, AuthorizedDate in transaction response

### ISSUE THREAD

**Issue by raj4all** [Ackara/Plaid.NET#28]
Hi,
The Entity.Transaction model is missing the 'Location/country' and 'authorized_date' fields which are specified in the Plaid documentation. 
https://plaid.com/docs/#transaction-schema
https://plaid.com/docs/#transaction-location-schema

**Comment by raj4all** [comment]
Also status object(below) is missing in _GetItemResponse_

"status": {
    "transactions": {
      "last_successful_update": "2019-02-15T15:10:00",
      "last_failed_update": "2019-01-22T04:32:00"
    },
    "last_webhook": {
      "sent_at": "2019-02-15T15:53:00",
      "code_sent": "DEFAULT_UPDATE"
    }
  }

Can I create a PR for this?

**Comment by Ackara** [comment]
Yes, go ahead

**Comment by raj4all** [comment]
Hi,
I am pushing a branch to upstream and getting below permission denied error.
I might be missing something basic. Can you please do the needful?
```
C:\Raj\Repos\Plaid.NET>git push --set-upstream origin raj-missing-fields
remote: Permission to Ackara/Plaid.NET.git denied to raj4all.
fatal: unable to access 'https://github.com/Ackara/Plaid.NET.git/': The requested URL returned error: 403
```

**Comment by viceroypenguin** [comment]
@raj4all  You do not have permission to edit this repository. You will need to create a Fork of this repo (the button in the top right), push the changes to your copy of the repo, and create a PR to this repo from there. See https://guides.github.com/activities/forking/ for more information.

**Comment by raj4all** [comment]
Thanks.
Created PR.
[Pull Request 36](https://github.com/Ackara/Plaid.NET/pull/36)

**Comment by viceroypenguin** [comment]
@raj4all  - I had the transaction fields, but not the status field in mine. I've updated to v1.1.2 this morning with the status field. Check out at https://github.com/viceroypenguin/Going.Plaid.NET

**Comment by raj4all** [comment]
@viceroypenguin ,
Thanks much.
So both are officially supported right?
_Install-Package Going.Plaid_ Vs _Install-Package Acklann.Plaid.NET_.

I am switching to **Going.Plaid** in my project's nuget.

**Comment by Ackara** [comment]
I merged and update the package
