### ISSUE TITLE
Tests requires secrets.json but no mention in README

### ISSUE THREAD

**Issue by thesuavehog** [Ackara/Plaid.NET#31]
Testing this repo (via tests/Plais.MSTest) requires a secrets.json file but there's no mention in the README of that file, it's format or what to put in it.

Could one be added to the repo (with fake values that need substitution) and the README updated to indicate it's format/use?

**Comment by Ackara** [comment]
Ok I will.  The secrets.json is at the root of the project and is contain the following

"plaid":
  {
    "secret": null,
    "client_id": null,
    "public_key": null,
    "access_token": null
  }
