### ISSUE TITLE
FetchInstitutionByIdAsync fails with clientId not a valid formatted client id

### ISSUE THREAD

**Issue by JulianGuppy** [Ackara/Plaid.NET#35]
Heres a snippet of my code using the client.FetchInstitutionByIdAsync() method I am in c# , using api end point version "2019-05-29" I am using nuget package version "v0.0.13-rc"

snippet
"
            var searchByIdRequest = new SearchByIdRequest
            {
                InstitutionId = institutionId,
                PublicKey = _plaidPublicKey,
            };
            var client = new PlaidClient(_plaidClientId, _plaidSecret, null, _plaidEnvironment, "2019-05-29");
            var task = Task.Run<SearchByIdResponse>(async () => await client.FetchInstitutionByIdAsync(searchByIdRequest));"

when I make this call I get an error message back saying that the clientId is missing, however it is supplied when I instantiate the plaidClient. when I have encountered this before in other methods I then added ClientId to the Request object, however this SearchByIdRequest object doesnt contain an item for me to Put the ClientId in the request...

I would appreciate a fix, a work around or a fix if you can please

Regards Julian

**Comment by thesuavehog** [comment]
I'm using the https://github.com/viceroypenguin/Going.Plaid.NET fork of this project so possibly there's a fix in there but when I use that library and the code below, it works for me.

```csharp
using Plaid_Institution = Going.Plaid.Entity.Institution;
public async Task<Plaid_Institution> GetInstitutionAsync(
	[DisallowNull] string accessToken,
	[DisallowNull] string institutionId)
{
	if (string.IsNullOrWhiteSpace(accessToken)) throw new ArgumentNullException(nameof(accessToken));
	if (string.IsNullOrWhiteSpace(institutionId)) throw new ArgumentNullException(nameof(institutionId));
	SearchByIdResponse institutionInfo = await _plaidClient.FetchInstitutionByIdAsync(
		new SearchByIdRequest()
		{
			AccessToken = accessToken,
			InstitutionId = institutionId,
			Options = new InstitutionSearchOptions() { IncludeOptionalMetadata = true }
		});
	if (!institutionInfo.IsSuccessStatusCode)
	{
		logger?.LogWarning("[{StatusCode}] Unable to obtain Instituion. Request ID: {RequestId}", institutionInfo.StatusCode, institutionInfo.RequestId);
		logger?.LogObjectDebug(institutionInfo);
		throw institutionInfo.Exception;
	}
	return institutionInfo.Institution;
}
```
