### ISSUE TITLE
NuGet does not find this package

### ISSUE THREAD

**Issue by ericpopivker** [Ackara/Plaid.NET#37]
I was trying to add your package in VS using NuGet and I get an error that this package is not found:
https://www.screencast.com/t/q5Sz37wi

**Comment by viceroypenguin** [comment]
Correction. It should be:
```powershell
PM > Install-Package Acklann.Plaid
```

**Comment by pdubb29** [comment]
For those using dotnet cli:
`dotnet add package Acklann.Plaid --version 0.0.15-rc`
