### ISSUE TITLE
Error in Vistal Studio 2019

### ISSUE THREAD

**Issue by omiddehghan2036** [Ackara/Plaid.NET#39]
Hi @Ackara !

Thank you for writing this library.
I use visual studio 2019, i can't run this project.
build project cannot run, and says the type of project is not compatible.
which version of visual studio or net framework i should use ?

**Comment by Ackara** [comment]
I use visual studio 2019 as well.
The build project is project type accessible via this [extension](https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2015)

The project contains some powershell scripts to upload the lib to nuget.
I does not affect the lib it self.

**Comment by omiddehghan2036** [comment]
Thank you for your reply.
I install that,but i have this error when i open the project .
this [Error](http://dl.takprogram.ir/plai-error.png)

**Comment by thesuavehog** [comment]
Try this extension for newer Visual Studio versions: https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561
