### ISSUE TITLE
Find access_token

### ISSUE THREAD

**Issue by omiddehghan2036** [Ackara/Plaid.NET#40]
Hello @Ackara .

How can i find access token for use library ?

**Comment by thesuavehog** [comment]
You need to sign up for a Plaid developer account. You will be given an access token for your account after signup.

**Comment by richardvaldiviesomacias** [comment]
Also, I am lost. I signed up for a Plaid developer, but I only have my plaid client id and the secret. Where is the access_token? Also, how can I get a public token?

**Comment by omiddehghan2036** [comment]
I have this error.
"Authentication failed because the remote party has closed the transport stream."
Could you help me ?

**Comment by Ackara** [comment]
To get the access token you first have to authenticate using "Plaid Link" in your product.

https://plaid.com/docs/quickstart/#how-it-works
