### ISSUE TITLE
Plaid swag?

### ISSUE THREAD

**Issue by phoenixy1** [Ackara/Plaid.NET#48]
@Ackara 

Apologies for filing an issue again but I don't have your contact info :-).  I just wanted to say thanks for your work maintaining this library, and as thank-you we'd like to send you a small Plaid care package. If you're interested, can you let me know your shipping address, t-shirt size, and if there are any items you'd particularly like? If you don't want to publish your address on GitHub you can DM me at @plaiddev or email me at ahoffer@plaid.com.

Thanks,
Alex

P.S. If you haven't already seen it, you might be interested in our newly-published [OpenAPI file](https://github.com/plaid/plaid-openapi), which is designed to make Plaid SDK generation easier -- we'd love to hear any feedback you might have!

**Comment by Ackara** [comment]
I appreciate the offer but I'm good on t-shirts.
