### ISSUE TITLE
Plaid linktoken and expiration are null

### ISSUE THREAD

**Issue by Shielaboba** [Ackara/Plaid.NET#58]
Hi, I tried running this locally, and it works perfectly fine, but on the  AWS Environment live server, there's no exception thrown and it returns linktoken and exception null.

Here's the code snippet:

`public async Task<CreateLinkTokenResult> GetPlaidLinkToken()
{
    var linkToken = await _client.CreateLinkToken(new CreateLinkTokenRequest()
    {
        ClientId = _clientId,
        Secret = _secret,
        User = new CreateLinkTokenRequest.UserInfo
        {
            ClientUserId = _userContext.CurrentUser.UserId,
        },
        CountryCodes = new[] { "US" },
        ClientName = "TestClient",
        Products = new[] { "transactions" }
    });
    return new CreateLinkTokenResult
    {
        Expiration = linkToken.Expiration,
        LinkToken = linkToken.LinkToken
    };
}`

And we always get this null result:
`
{
  "data": {
    "linkToken": null,
    "expiration": null
  },
  "exception": null,
  "errorMessage": "",
  "statusCode": 200
}
`

The result should not be nullable. Hope you guys have an idea on this.

**Comment by viceroypenguin** [comment]
If you switch to Going.Plaid, you can turn on `ShowRawJson` to see the full response you're getting from Plaid. Maybe the json is getting manipulated in the AWS Environment.

**Comment by Shielaboba** [comment]
Does it only support .NET 5 up?

**Comment by viceroypenguin** [comment]
It's designed for .NET 5, but I've tested it with .NET Core 3.1 and it's worked well for me.

**Comment by Shielaboba** [comment]
Oh I see. I got this error while trying to set value on ClientUserId for creating a linktoken, init-only setter is not available in C# 8.0. I think it only supports C# 9 up which is .NET5

**Comment by viceroypenguin** [comment]
You can use C# 9 or C# 10 with .NET Core 3.1. The only restriction with a higher language and a lower core version is that you can't use certain features that depend on objects in the later frameworks. You may need to set the `<LangVersion />` tag in the .csproj to 9, however.

I had not considered the `init`-only setters being a problem w/ C# 8. If you use a C# 8 compiler, it won't complain. Only a C# 9 compiler set to language version 8 will complain. I may make some changes for that, though. Thanks for letting me know!

**Comment by Shielaboba** [comment]
Yeah right! I'll try it. Thanks for helping!

**Comment by Shielaboba** [comment]
Going.Plaid fixed our issue. Thanks! Will close this ticket now.
