### ISSUE TITLE
No assets endpoints anymore?

### ISSUE THREAD

**Issue by andrew-lewell** [Ackara/Plaid.NET#63]
PlaidClient.cs seems to be missing all asset report related endpoints such as /asset_report/refresh and /asset_report/create

**Comment by viceroypenguin** [comment]
@andrew-lewell please check out the Going.Plaid nuget package. I have automated all APIs that are provided by the Plaid documentation.

**Comment by andrew-lewell** [comment]
Great, thanks for clarifying!
