### ISSUE TITLE
Waiting for Activation

### ISSUE THREAD

**Issue by ISatByTheO** [Ackara/Plaid.NET#7]
When I attempt to exchange tokens I just receive "Waiting for activation" - Do you know why this is occurring?

I've tried to await the request but I am never able to get back into debugging a response with the access-token.

Any information would be appreciated!

**Comment by keval-gangani** [comment]
I'm getting same message "Waiting for Activation".

@ISatByTheO Did you get any solution of this message from Plaid? If yes then please share here, that would be helpful for me.

**Comment by ISatByTheO** [comment]
Hey @keval I ended up writing my own client, it just made more sense and only took like 3 days to get all of the end points in. You can just download the postman collection, build your c# objects from their responses and then generically parse the json data to your c# objects. I can send you some code snippets tomorrow if that helps?

**Comment by keval-gangani** [comment]
@ISatByTheO That's awesome. I will be waiting for your code snippet. I were also think about to develop own library.

**Comment by keval-gangani** [comment]
@ISatByTheO 

Can you please share some sample code?

**Comment by Ackara** [comment]
If you fix it I will accept the pull request.
